[workspace]
members = [
    "examples/*"
]

[package]
name = "bevy-kira-components"
description = "Alternative crate for Bevy integration of Kira"
license = "MIT"
license-file = "LICENSE"
homepage = "https://github.com/solarliner/bevy-kira-components"
repository = "https://github.com/solarliner/bevy-kira-components.git"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kira = { version = "0.8.7", features = ["serde"] }
thiserror = "1.0.57"
serde = { version = "1.0.197", features = ["derive"] }

[dependencies.bevy]
version = "0.13.0"
default-features = false
features = ["bevy_asset"]

[features]
default = []
diagnostics = []
